### ISSUE TITLE
test framework does not report IsolateSpawnException

### ISSUE THREAD

**Issue by karlklose** [peter-ahe-google/testing#1]
```:dart  ./pkg/kernel/test/closures_test.dart
00:00 +0: closures
IsolateSpawnException: Unable to spawn isolate: Unhandled exception:
Could not import "package:testing/src/run_tests.dart" from "data:,library%20testing.generated;%0A%0Aimport%20'dart:async'%20show%20Future;%0A%0Aimport%20'dart:convert'%20show%20JSON;%0A%0Aimport%20'package:testing/src/run_tests.dart'%20show%20runTests;%0A%0Aimport%20'package:testing/src/chain.dart'%20show%20runChain;%0A%0Aimport%20'package:testing/src/log.dart'%20show%20enableVerboseOutput,%20isVerbose;%0A%0Aimport%20'file:///usr/local/google/home/karlklose/ssd/workspace/dart/sdk/pkg/kernel/test/closures/suite.dart'%20as%20closures;%0A%0AFuture%3CNull%3E%20main()%20async%20%7B%0A%20%20if%20(false)%20enableVerboseOutput();%0A%20%20Map%3CString,%20String%3E%20environment%20=%20JSON.decode('%7B%7D');%0A%20%20await%20runTests(%3CString,%20Function%3E%20%7B%0A%20%20%20%20%20%20%0A%20%20%7D);%0A%20%20runChain(closures.createContext,%20environment,%20r'''%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22name%22:%20%22closures%22,%0A%20%20%20%20%20%20%20%20%22kind%22:%20%22chain%22,%0A%20%20%20%20%20%20%20%20%22source%22:%20%22file:///usr/local/google/home/karlklose/ssd/workspace/dart/sdk/pkg/kernel/test/closures/suite.dart%22,%0A%20%20%20%20%20%20%20%20%22path%22:%20%22file:///usr/local/google/home/karlklose/ssd/workspace/dart/sdk/pkg/kernel/test/closures/%22,%0A%20%20%20%20%20%20%20%20%22status%22:%20%22file:///usr/local/google/home/karlklose/ssd/workspace/dart/sdk/pkg/kernel/test/closures/closures.status%22,%0A%20%20%20%20%20%20%20%20%22pattern%22:%20%5B%0A%20%20%20%20%20%20%20%20%20%20%22%5C%5C.dart$%22%0A%20%20%20%20%20%20%20%20%5D,%0A%20%20%20%20%20%20%20%20%22exclude%22:%20%5B%0A%20%20%20%20%20%20%20%20%20%20%22/test/closures/suite%5C%5C.dart$%22%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%7D''');%0A%7D%0A": Packages file 'file:///usr/local/google/home/karlklose/ssd/workspace/dart/sdk/pkg/.packages' not found.
null
#0      Isolate.spawnUri.<spawnUri_async_body> (dart:isolate-patch/isolate_patch.dart)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      StackZoneSpecification._registerBinaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:26)
#3      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185:15)
#4      StackZoneSpecification._registerBinaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:14)
#5      _rootRunBinary (dart:async/zone.dart:1170)
#6      _CustomZone.runBinary (dart:async/zone.dart:1049)
#7      _FutureListener.handleError (dart:async/future_impl.dart:146)
#8      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#10     _Future._completeError (dart:async/future_impl.dart:485)
#11     _SyncCompleter._completeError (dart:async/future_impl.dart:56)
#12     _Completer.completeError (dart:async/future_impl.dart:27)
#13     Isolate._spawnCommon.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:443)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

00:00 +1: All tests passed!
```

**Comment by wutthichai46** [comment]
> ```:dart  ./pkg/kernel/test/closures_test.dart
> 00:00 +0: closures
> IsolateSpawnException: Unable to spawn isolate: Unhandled exception:
> Could not import "package:testing/src/run_tests.dart" from "data:,library%20testing.generated;%0A%0Aimport%20'dart:async'%20show%20Future;%0A%0Aimport%20'dart:convert'%20show%20JSON;%0A%0Aimport%20'package:testing/src/run_tests.dart'%20show%20runTests;%0A%0Aimport%20'package:testing/src/chain.dart'%20show%20runChain;%0A%0Aimport%20'package:testing/src/log.dart'%20show%20enableVerboseOutput,%20isVerbose;%0A%0Aimport%20'file:///usr/local/google/home/karlklose/ssd/workspace/dart/sdk/pkg/kernel/test/closures/suite.dart'%20as%20closures;%0A%0AFuture%3CNull%3E%20main()%20async%20%7B%0A%20%20if%20(false)%20enableVerboseOutput();%0A%20%20Map%3CString,%20String%3E%20environment%20=%20JSON.decode('%7B%7D');%0A%20%20await%20runTests(%3CString,%20Function%3E%20%7B%0A%20%20%20%20%20%20%0A%20%20%7D);%0A%20%20runChain(closures.createContext,%20environment,%20r'''%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22name%22:%20%22closures%22,%0A%20%20%20%20%20%20%20%20%22kind%22:%20%22chain%22,%0A%20%20%20%20%20%20%20%20%22source%22:%20%22file:///usr/local/google/home/karlklose/ssd/workspace/dart/sdk/pkg/kernel/test/closures/suite.dart%22,%0A%20%20%20%20%20%20%20%20%22path%22:%20%22file:///usr/local/google/home/karlklose/ssd/workspace/dart/sdk/pkg/kernel/test/closures/%22,%0A%20%20%20%20%20%20%20%20%22status%22:%20%22file:///usr/local/google/home/karlklose/ssd/workspace/dart/sdk/pkg/kernel/test/closures/closures.status%22,%0A%20%20%20%20%20%20%20%20%22pattern%22:%20%5B%0A%20%20%20%20%20%20%20%20%20%20%22%5C%5C.dart$%22%0A%20%20%20%20%20%20%20%20%5D,%0A%20%20%20%20%20%20%20%20%22exclude%22:%20%5B%0A%20%20%20%20%20%20%20%20%20%20%22/test/closures/suite%5C%5C.dart$%22%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%7D''');%0A%7D%0A": Packages file 'file:///usr/local/google/home/karlklose/ssd/workspace/dart/sdk/pkg/.packages' not found.
> null
> #0      Isolate.spawnUri.<spawnUri_async_body> (dart:isolate-patch/isolate_patch.dart)
> #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
> #2      StackZoneSpecification._registerBinaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:26)
> #3      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185:15)
> #4      StackZoneSpecification._registerBinaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:14)
> #5      _rootRunBinary (dart:async/zone.dart:1170)
> #6      _CustomZone.runBinary (dart:async/zone.dart:1049)
> #7      _FutureListener.handleError (dart:async/future_impl.dart:146)
> #8      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
> #9      _Future._propagateToListeners (dart:async/future_impl.dart:671)
> #10     _Future._completeError (dart:async/future_impl.dart:485)
> #11     _SyncCompleter._completeError (dart:async/future_impl.dart:56)
> #12     _Completer.completeError (dart:async/future_impl.dart:27)
> #13     Isolate._spawnCommon.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:443)
> #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
> 
> 00:00 +1: All tests passed!
> ```
